### ISSUE TITLE
Compilation error on MacOS 

### ISSUE THREAD

**Issue by cchampet** [tuttleofx/TuttleOFX#454]
With boost-1.58

OfxhImageEffectPlugin.hpp:74:2: error: no type named 'mutex' in namespace 'boost'; did you mean 'std::mutex'?

OfxhImageEffectPlugin.cpp:191:2: error: no member named 'mutex' in namespace 'boost'; did you mean 'std::mutex'?

**Comment by fabiencastan** [comment]
It works with boost 1.58 on linux.

Could you try to add the needed include in OfxhImageEffectPlugin.hpp?
`#include <boost/thread/mutex.hpp>`

May depend on the boost compilation flag: BOOST_THREAD_PLATFORM_PTHREAD.

**Comment by cchampet** [comment]
Well done! Checkout PR #455
